///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package blog

import (
	"fmt"
	"time"

	"github.com/xinliangnote/go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *Blog {
	return new(Blog)
}

func NewQueryBuilder() *blogQueryBuilder {
	return new(blogQueryBuilder)
}

func (t *Blog) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.AID, nil
}

type blogQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *blogQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *blogQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&Blog{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *blogQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&Blog{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *blogQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&Blog{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *blogQueryBuilder) First(db *gorm.DB) (*Blog, error) {
	ret := &Blog{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *blogQueryBuilder) QueryOne(db *gorm.DB) (*Blog, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *blogQueryBuilder) QueryAll(db *gorm.DB) ([]*Blog, error) {
	var ret []*Blog
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *blogQueryBuilder) Limit(limit int) *blogQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *blogQueryBuilder) Offset(offset int) *blogQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *blogQueryBuilder) WhereAID(p mysql.Predicate, value int32) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "a_id", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereAIDIn(value []int32) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "a_id", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereAIDNotIn(value []int32) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "a_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByAID(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "a_id "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereAuthor(p mysql.Predicate, value string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "author", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereAuthorIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "author", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereAuthorNotIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "author", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByAuthor(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "author "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereCategory(p mysql.Predicate, value string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "category", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereCategoryIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "category", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereCategoryNotIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "category", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByCategory(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "category "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereTitle(p mysql.Predicate, value string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereTitleIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereTitleNotIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByTitle(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "title "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereContent(p mysql.Predicate, value string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereContentIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereContentNotIn(value []string) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByContent(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "content "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereStatusIn(value []int32) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereStatusNotIn(value []int32) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByStatus(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereAddTime(p mysql.Predicate, value time.Time) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "add_time", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereAddTimeIn(value []time.Time) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "add_time", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereAddTimeNotIn(value []time.Time) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "add_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByAddTime(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "add_time "+order)
	return qb
}

func (qb *blogQueryBuilder) WhereUpdateTime(p mysql.Predicate, value time.Time) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "update_time", p),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereUpdateTimeIn(value []time.Time) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "update_time", "IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) WhereUpdateTimeNotIn(value []time.Time) *blogQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "update_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *blogQueryBuilder) OrderByUpdateTime(asc bool) *blogQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "update_time "+order)
	return qb
}
